library(shiny)

dynMap <- function(inputoutputId) 
{
    div(id = inputoutputId, class="d3map")
}

# Define UI for application that plots random distributions 
shinyUI(pageWithSidebar(
    
    # Application title
    headerPanel("Putting Down Roots: A Graphical Exploration of Community Attachment",
                windowTitle = "Putting Down Roots"),
    
    sidebarPanel(
        helpText(HTML("<p>Exploratory tool by <a href=\"http://www.andeekaplan.com\" target=\"_blank\">Andee Kaplan</a> and Eric Hare based on <a href=\"http://www.soulofthecommunity.org/\" target=\"_blank\">'Soul of the Community'</a> data generated by the Knight Foundation in cooperation with Gallup. Project was created as part of the <a href=\"http://streaming.stat.iastate.edu/dataexpo/2013/\" target=\"_blank\">2013 Data Exposition</a>.</p><p>Further details pertaining to the data can be found in the accompanying <a href='http://harekaplan.github.io/dataexpo2013/Poster_DataExpo2013_Kaplan_Hare.pdf' target='_blank'>poster</a>.<p>")),
        includeHTML("scripts/graph.js"),
        includeHTML("css/map_style.css"),
        includeHTML("css/graphs_style.css"),
        includeHTML("css/button_style.css"),
        includeHTML("css/table_style.css"),    
        div(id='namewrapper', 
            div(id='left', HTML('<a href=\"http://www.andeekaplan.com\" target=\"_blank\">Andee Kaplan</a><br/>Dept. of Statistics<br/>Iowa State University')),
            div(id='right', HTML('Eric Hare<br/>Dept. of Statistics<br/>Iowa State University'))
        ),
        div(class='controls',
            checkboxInput("aggregate", "Aggregate all years", TRUE),
            conditionalPanel(
                condition = "input.aggregate == false",
                sliderInput("year", "Choose year:", 
                            min = 2008, max = 2010, value = 2008, step = 1,
                            format="####")
            )
        )
    ),
    
    mainPanel(
        dynMap(inputoutputId = 'd3io')
    )
))
